### ISSUE TITLE
[BUG] macOS 11 Incompatibility

### ISSUE THREAD

**Issue by noblesoul7** [yuanzhoucq/Tab-Space#34] opened 2020-06-30 01:03 UTC
Tab Space does not function in Safari on macOS 11 Big Sur, beta 1. Sometimes there's a hint of the corner of the menu, but otherwise its menu does not display at all.

I'm not sure if this is on your radar yet, but I'm excited to use it on the new macOS. :)

**Comment by yuanzhoucq** [comment] 2020-06-30 01:20
Thanks for your feedbacks! I am very willing to fix this. But I have only one Mac and many other work to do with it. So I cannot upgrade it immediately. 

I have ordered a new Mac (the Developer Translation Kit) which should have built-in macOS 11. So I will be able to fix this bug once I have it. Approximately the new Mac will arrive in two weeks. And sorry for this waiting period : (

**Comment by yuanzhoucq** [comment] 2020-06-30 01:24
And for now I think the shortcuts should still work? For example, use `Ctrl + T` to open Tab Space? Note that it should be triggered within a normal web page when the address bar is not empty.

**Comment by noblesoul7** [comment] 2020-06-30 19:56
That was a great suggestion! It did open Tab Space. However, I cannot import my backup file. :( I can select it, but nothing changes in Tab Space. I was able to save a new tab with a shortcut though, so it seems like Tab Space is working.

What folders are Tab Space's files saved in? I want to try copying them from my old installation.

**Comment by yuanzhoucq** [comment] 2020-07-01 00:05
> However, I cannot import my backup file. 

Wait, why would you need import it? Do you mean that you lost saved data after upgrading? 😳

**Comment by noblesoul7** [comment] 2020-07-01 01:13
Oh, no! I created a fresh installation of Big Sur, and wanted to import my tabs from my old installation.

**Comment by yuanzhoucq** [comment] 2020-07-01 01:21
OK, that sounds much better to me : )

If you login the same Apple ID and enable iCloud, the sessions should be synced automatically.

And the importing function should work as well. But I also need to wait for the new Mac to confirm it.

**Comment by noblesoul7** [comment] 2020-07-01 20:04
Unfortunately, I also started using a new iCloud account! 😔

But I created another user account with my old iCloud, and yes, Tab Space does restore from iCloud, so I imagine most people are okay!

But importing the backup into my new account does not work. I also tried copying over the folders from ~/Library, but that method isn't working either. I will just have to be patient for your updates. :)

**Comment by yuanzhoucq** [comment] 2020-07-09 02:35
Hi @noblesoul7 

Sorry I just noticed your updates. These files you copied are controlled by iCloud automatically. So perhaps it won't be transferred to another account directly. 

To get Tab Space up again, I suggest you to delete this `Application Support/Tab-Works Extension` folder edited manually and restart Safari. 

I still have no idea why the importing doesn’t work. If there isn’t any sensitive information in your backup, could you please share it to me via email (joyuercn@icloud.com)?  And I will be able to investigate the cause.

**Comment by noblesoul7** [comment] 2020-07-12 16:12
Thanks for the offer. But it appears to be working now on beta 2 via shortcuts! I'm not sure what was happening in beta 1, but import didn't seem to work.

I deleted Tab Space from two Macs with App Cleaner (to delete all the edited library files), reinstalled it, imported the backup file, and now Tab Space is working. It did eventually sync to another Mac, but I'm seeing that some newly saved tabs have not synched, so synching may be slow or have a different issue.

**Comment by webrockers** [comment] 2020-08-04 12:12
Any news on that issue?

**Comment by yuanzhoucq** [comment] 2020-08-04 14:47
@webrockers I contacted Apple team and they confirmed that this is a bug on their side and there would be a fix soon. So I waited for a month until now... 😢

If this bug persists and they could not fix it in a short time, I am considering simulating a menu using the popover window, which will be something like this:

![image](https://user-images.githubusercontent.com/31144612/89308040-61157c00-d6a4-11ea-89dd-633e789fbe0b.png)

**Comment by yuanzhoucq** [comment] 2020-08-19 07:00
![image](https://user-images.githubusercontent.com/31144612/90602383-4575ae00-e22c-11ea-87aa-72a3b8aaa53c.png)

Finally I change a little the design and make it work on macOS Big Sur. In addition now you can append a session directly to an existing one. Will be available in a few days from Mac App Store. And any further suggestions are welcome : )

**Closed** 2020-08-31 02:27 UTC

**Comment by gingerbeardman** [comment] 2020-08-31 10:26
Just got the update - great!
