### ISSUE TITLE
[Feature] Privacy policy?

### ISSUE THREAD

**Issue by skobylite** [yuanzhoucq/Tab-Space#33] opened 2020-06-26 08:25 UTC
I love the idea of this - my only concern is the 'view and edit all text on websites', is there any privacy guarantee with this?

**Comment by yuanzhoucq** [comment] 2020-06-26 08:28
Hello, it is completely reasonable to ask about this, please refer to #15. Any further questions are welcome as well : )

**Comment by yuanzhoucq** [comment] 2020-06-26 08:31
Duplicate of #15

**Closed** 2020-06-29 08:53 UTC
