### ISSUE TITLE
Feature Request -- disable (some or all) keyboard shortcuts

### ISSUE THREAD

**Issue by cori** [yuanzhoucq/Tab-Space#27] opened 2020-06-10 19:26 UTC
I love Tab Space and have used it pretty heavily since I moved from Chrome to Safari, but I've had to move away from it because I use services that rely on some of the built-in shortcuts that Tab Space provides. Any level of ability to configure those shortcuts would be great so I don't have to choose between the services I use and the extension.

Ideally these shortcuts would be maintained in the macOS Keyboard System Preferences, although I don't know if that's possible from within a Safari Extension.

**Comment by adamshand** [comment] 2020-06-11 00:21
Tab Spaces is a lovely program but I'm extremely frustrated right now.  

For a couple weeks I've been wondering why CTRL-D doesn't work as expected anymore (CTRL-D is a standard Emacs keybinding for deleting the character to the right of the cursor).  I use CTRL-D in Safari all the time when editing text.

I just spent a couple hours trying to track this down and eventually figured out it was Tab Space by disabling all of my Safari extensions and re-enabling them one by one.

PLEASE DON'T CREATE SHORTCUTS THAT OVERLAP WITH STANDARD MACOS SHORTCUTS.  Ideally shortcuts would be registered in "System Preferences - Keyboard - Shortcuts".  If that's not technically possible at least make them configurable in the app itself.  

Also Safari has a "Duplicate Tab" menu item which anyone can assign a shortcut to.

Until this is fixed I've sadly had to disable the extension.

**Comment by cori** [comment] 2020-06-11 11:46
> I just spent a couple hours trying to track this down

Ha I had the same experience and ended up using `opensnoop` in my macOS terminal to figure out what was opening Chrome on Ctrl+C in Safari.

**Comment by yuanzhoucq** [comment] 2020-06-11 14:44
> I love Tab Space and have used it pretty heavily since I moved from Chrome to Safari, but I've had to move away from it because I use services that rely on some of the built-in shortcuts that Tab Space provides. Any level of ability to configure those shortcuts would be great so I don't have to choose between the services I use and the extension.
> 
> Ideally these shortcuts would be maintained in the macOS Keyboard System Preferences, although I don't know if that's possible from within a Safari Extension.


Hello there, did you try the option “disable shortcuts” in the settings page? I think this should give back the control of the shortcuts needed by the services to you. Configuring shortcuts in the system preferences seems impossible to me for the extensions because as far as I know, this way only works for menus. But extension could not inject content to Safari’s menu. 

Please tell me if the “disable shortcuts” does not solve your problem. 😄

**Comment by yuanzhoucq** [comment] 2020-06-11 14:51
> PLEASE DON'T CREATE SHORTCUTS THAT OVERLAP WITH STANDARD MACOS SHORTCUTS. 

@adamshand Sorry for the trouble caused by Tab Space’s shortcuts. When I initially choose these shortcuts I did not know they have already taken by other common used functions. But if you don’t need the shortcuts, at least you can disable them all for now. This should give these shortcuts back to you and you will not need to disable the extension itself.

And I will try to figure out some solution to make the shortcuts configurable in later versions : )

**Comment by adamshand** [comment] 2020-06-13 04:12
@yuanzhoucq thank you very much, sorry for being grumpy!

**Comment by adamshand** [comment] 2020-06-13 04:29
Sorry I think I'm being dumb.  Where do I find the setting to disable the settings?  I don't see any options in the app itself (I'm running 3.7 which I think is the latest?) or anything in Safari.

**Comment by yuanzhoucq** [comment] 2020-06-13 13:12
> Sorry I think I'm being dumb.  Where do I find the setting to disable the settings?  I don't see any options in the app itself (I'm running 3.7 which I think is the latest?) or anything in Safari.  

In the Tab Space page inside Safari (where you view your saved tabs), there is a “settings” button in the top-right corner.

**Comment by yuanzhoucq** [comment] 2020-06-17 03:10
I assume that your problems have been solved so I will close this issue. If there are still obstacles using Tab Space, you are welcome to reopen it : )

**Closed by yuanzhoucq** 2020-06-17 03:10 UTC

**Comment by adamshand** [comment] 2020-06-17 04:46
Resolved, many thanks!
